# .github/workflows/deploy.yml
# Auto-deploys to Render whenever you push to main branch

name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
        # Add RENDER_DEPLOY_HOOK in GitHub repo Settings → Secrets
        # Get the hook URL from Render dashboard → your service → Settings → Deploy Hook
